FROM golang:1.27 AS build

RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.22

COPY --from=build /go/bin/goose /usr/local/bin/goose

WORKDIR /src
COPY db/sql/migrations/ /migrations/

CMD goose -dir /migrations postgres "$DB_CONN_STR" up
